using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using Windows.Storage.Pickers;
using WinRequest.Models;
using WinRequest.Services;

namespace WinRequest.Controls;

public sealed partial class KeyValueTable : UserControl
{
    private bool _suppressChanged;
    private bool _showAutoGeneratedHeaders;
    private Func<List<string>>? _variableNamesProvider;
    private Grid? _autoCompleteHostGrid;
    private readonly List<VariableAutoComplete> _autoCompletes = new();
    private static readonly IReadOnlyList<KeyValuePairItem> DefaultAutoGeneratedHeaders =
    [
        new() { Key = "Cache-Control", Value = "no-cache", Enabled = true, IsAutoGenerated = true, IsLocked = true },
        new() { Key = "WinRequest-Token", Value = "<calculated when request is sent>", Enabled = true, IsAutoGenerated = true, IsLocked = true },
        new() { Key = "Host", Value = "<calculated when request is sent>", Enabled = true, IsAutoGenerated = true },
        new() { Key = "User-Agent", Value = "WinRequestRuntime/1.0.0", Enabled = true, IsAutoGenerated = true },
        new() { Key = "Accept", Value = "*/*", Enabled = true, IsAutoGenerated = true },
        new() { Key = "Accept-Encoding", Value = "gzip, deflate, br", Enabled = true, IsAutoGenerated = true },
        new() { Key = "Connection", Value = "keep-alive", Enabled = true, IsAutoGenerated = true }
    ];

    public static readonly DependencyProperty KeyPlaceholderTextProperty =
        DependencyProperty.Register(nameof(KeyPlaceholderText), typeof(string), typeof(KeyValueTable), new PropertyMetadata("Key"));

    public static readonly DependencyProperty ValuePlaceholderTextProperty =
        DependencyProperty.Register(nameof(ValuePlaceholderText), typeof(string), typeof(KeyValueTable), new PropertyMetadata("Value"));

    public static readonly DependencyProperty DescriptionPlaceholderTextProperty =
        DependencyProperty.Register(nameof(DescriptionPlaceholderText), typeof(string), typeof(KeyValueTable), new PropertyMetadata("Description"));

    public static readonly DependencyProperty SupportsValueKindProperty =
        DependencyProperty.Register(nameof(SupportsValueKind), typeof(bool), typeof(KeyValueTable), new PropertyMetadata(false, OnSupportsValueKindChanged));

    public static readonly DependencyProperty SupportsAutoGeneratedHeadersProperty =
        DependencyProperty.Register(nameof(SupportsAutoGeneratedHeaders), typeof(bool), typeof(KeyValueTable), new PropertyMetadata(false, OnSupportsAutoGeneratedHeadersChanged));

    public KeyValueTable()
    {
        InitializeComponent();
    }

    public event EventHandler? ItemsChanged;

    public string KeyPlaceholderText
    {
        get => (string)GetValue(KeyPlaceholderTextProperty);
        set => SetValue(KeyPlaceholderTextProperty, value);
    }

    public string ValuePlaceholderText
    {
        get => (string)GetValue(ValuePlaceholderTextProperty);
        set => SetValue(ValuePlaceholderTextProperty, value);
    }

    public string DescriptionPlaceholderText
    {
        get => (string)GetValue(DescriptionPlaceholderTextProperty);
        set => SetValue(DescriptionPlaceholderTextProperty, value);
    }

    public bool SupportsValueKind
    {
        get => (bool)GetValue(SupportsValueKindProperty);
        set => SetValue(SupportsValueKindProperty, value);
    }

    public bool SupportsAutoGeneratedHeaders
    {
        get => (bool)GetValue(SupportsAutoGeneratedHeadersProperty);
        set => SetValue(SupportsAutoGeneratedHeadersProperty, value);
    }

    public void EnableVariableAutoComplete(Grid hostGrid, Func<List<string>> getVariableNames)
    {
        _autoCompleteHostGrid = hostGrid;
        _variableNamesProvider = getVariableNames;
    }

    public void SetItems(IEnumerable<KeyValuePairItem> items)
    {
        _suppressChanged = true;
        RowsPanel.Children.Clear();
        DisposeAutoCompletes();

        var tableItems = SupportsAutoGeneratedHeaders
            ? MergeAutoGeneratedHeaders(items)
            : items.Select(CloneItem).ToList();

        foreach (var item in tableItems)
            AddRow(item.Enabled, item.Key, item.Value, item.Description, item.ValueKind, item.IsAutoGenerated, item.IsLocked);

        if (RowsPanel.Children.Count == 0)
            AddRow(true, "", "", "", KeyValueValueKind.Text, false, false);

        UpdateAutoGeneratedHeadersVisibility();
        _suppressChanged = false;
    }

    public List<KeyValuePairItem> GetItems()
    {
        var result = new List<KeyValuePairItem>();
        foreach (UIElement child in RowsPanel.Children)
        {
            if (child is not Grid row)
                continue;

            var checkBox = FindChild<CheckBox>(row, "RowCheckBox");
            var keyBox = FindChild<TextBox>(row, "RowKeyBox");
            var valueBox = FindChild<TextBox>(row, "RowValueBox");
            var descriptionBox = FindChild<TextBox>(row, "RowDescriptionBox");
            var valueKindBox = FindChild<ComboBox>(row, "RowValueKindBox");

            if (keyBox == null)
                continue;

            string key = keyBox.Text?.Trim() ?? "";
            if (string.IsNullOrWhiteSpace(key))
                continue;

            result.Add(new KeyValuePairItem
            {
                Key = key,
                Value = valueBox?.Text ?? "",
                ValueKind = SupportsValueKind ? GetSelectedValueKind(valueKindBox) : KeyValueValueKind.Text,
                Description = descriptionBox?.Text ?? "",
                Enabled = checkBox?.IsChecked ?? true,
                IsAutoGenerated = row.Tag is KeyValuePairItem { IsAutoGenerated: true },
                IsLocked = row.Tag is KeyValuePairItem { IsLocked: true }
            });
        }
        return result;
    }

    private void AddRow(bool enabled, string key, string value, string description, KeyValueValueKind valueKind, bool isAutoGenerated, bool isLocked)
    {
        var row = new Grid
        {
            Tag = new KeyValuePairItem { IsAutoGenerated = isAutoGenerated, IsLocked = isLocked },
            ColumnSpacing = 0,
            Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.White),
            BorderBrush = (Microsoft.UI.Xaml.Media.Brush)Application.Current.Resources["WorkbenchSubtleStrokeBrush"],
            BorderThickness = new Thickness(0, 0, 0, 1)
        };
        row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(30) });
        row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        row.ColumnDefinitions.Add(new ColumnDefinition { Width = SupportsValueKind ? new GridLength(92) : new GridLength(0) });
        row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1.2, GridUnitType.Star) });
        row.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(30) });

        var checkBox = new CheckBox
        {
            Name = "RowCheckBox",
            IsChecked = isLocked || enabled,
            IsEnabled = !isLocked,
            Style = (Style)Resources["CellCheckBoxStyle"]
        };
        checkBox.Checked += Row_FieldChanged;
        checkBox.Unchecked += Row_FieldChanged;
        Grid.SetColumn(checkBox, 0);

        var keyBox = CreateCellTextBox("RowKeyBox", key, KeyPlaceholderText, true);
        keyBox.IsReadOnly = isAutoGenerated;
        keyBox.TextChanged += Row_FieldChanged;
        Grid.SetColumn(keyBox, 1);

        var valueBox = CreateCellTextBox("RowValueBox", value, ValuePlaceholderText, true);
        valueBox.IsReadOnly = isAutoGenerated;
        valueBox.TextChanged += Row_FieldChanged;
        Grid.SetColumn(valueBox, 3);

        ComboBox? valueKindBox = null;
        if (SupportsValueKind)
        {
            valueKindBox = CreateValueKindComboBox(valueKind);
            valueKindBox.SelectionChanged += RowValueKindBox_SelectionChanged;
            Grid.SetColumn(valueKindBox, 2);
        }

        var filePickerPanel = CreateFilePickerPanel(value);
        Grid.SetColumn(filePickerPanel, 3);

        var descriptionBox = CreateCellTextBox("RowDescriptionBox", description, DescriptionPlaceholderText, false);
        descriptionBox.IsReadOnly = isAutoGenerated;
        descriptionBox.TextChanged += Row_FieldChanged;
        Grid.SetColumn(descriptionBox, 4);

        if (_variableNamesProvider != null && _autoCompleteHostGrid != null)
        {
            var ac = new VariableAutoComplete(valueBox, _autoCompleteHostGrid, _variableNamesProvider);
            _autoCompletes.Add(ac);
        }

        var deleteButton = new Button
        {
            Padding = new Thickness(4, 2, 4, 2),
            MinWidth = 28,
            MinHeight = 28,
            Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Transparent),
            BorderThickness = new Thickness(0),
            VerticalAlignment = VerticalAlignment.Center,
            Visibility = isAutoGenerated ? Visibility.Collapsed : Visibility.Visible
        };
        deleteButton.Content = new FontIcon { Glyph = "\uE74D", FontSize = 11 };
        deleteButton.Click += DeleteRow_Click;
        ToolTipService.SetToolTip(deleteButton, "Delete");
        Grid.SetColumn(deleteButton, 5);

        row.Children.Add(checkBox);
        row.Children.Add(keyBox);
        if (valueKindBox != null)
            row.Children.Add(valueKindBox);
        row.Children.Add(valueBox);
        row.Children.Add(filePickerPanel);
        row.Children.Add(descriptionBox);
        row.Children.Add(deleteButton);

        RowsPanel.Children.Add(row);
        UpdateValueKindVisualState(row);
        UpdateAutoGeneratedHeadersVisibility(row);
    }

    private ComboBox CreateValueKindComboBox(KeyValueValueKind valueKind)
    {
        var comboBox = new ComboBox
        {
            Name = "RowValueKindBox",
            MinWidth = 82,
            Height = 32,
            Margin = new Thickness(4, 2, 4, 2),
            VerticalAlignment = VerticalAlignment.Center,
            HorizontalAlignment = HorizontalAlignment.Stretch
        };
        comboBox.Items.Add(new ComboBoxItem { Content = "Text", Tag = KeyValueValueKind.Text });
        comboBox.Items.Add(new ComboBoxItem { Content = "File", Tag = KeyValueValueKind.File });
        comboBox.SelectedIndex = valueKind == KeyValueValueKind.File ? 1 : 0;
        return comboBox;
    }

    private Grid CreateFilePickerPanel(string path)
    {
        var panel = new Grid
        {
            Name = "RowFilePickerPanel",
            Visibility = Visibility.Collapsed,
            Padding = new Thickness(6, 3, 6, 3),
            ColumnSpacing = 6,
            VerticalAlignment = VerticalAlignment.Stretch
        };
        panel.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });
        panel.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });

        var button = new Button
        {
            Name = "RowFilePickerButton",
            Height = 30,
            Padding = new Thickness(10, 4, 10, 4),
            VerticalAlignment = VerticalAlignment.Center
        };
        button.Content = new StackPanel
        {
            Orientation = Orientation.Horizontal,
            Spacing = 5,
            Children =
            {
                new FontIcon { Glyph = "\uE838", FontSize = 12 },
                new TextBlock { Text = "Choose file", FontSize = 12, VerticalAlignment = VerticalAlignment.Center }
            }
        };
        button.Click += SelectFormFile_Click;
        ToolTipService.SetToolTip(button, "Choose file");

        var pathText = new TextBlock
        {
            Name = "RowFilePathText",
            Text = path,
            VerticalAlignment = VerticalAlignment.Center,
            FontSize = 12,
            Foreground = (Brush)Application.Current.Resources["TextFillColorSecondaryBrush"],
            TextTrimming = TextTrimming.CharacterEllipsis
        };
        Grid.SetColumn(pathText, 1);

        panel.Children.Add(button);
        panel.Children.Add(pathText);
        return panel;
    }

    private TextBox CreateCellTextBox(string name, string text, string placeholder, bool mono)
    {
        var textBox = new TextBox
        {
            Name = name,
            Text = text,
            PlaceholderText = placeholder,
            Style = (Style)Resources["CellTextBoxStyle"],
            IsSpellCheckEnabled = false,
            IsTextPredictionEnabled = false
        };

        if (mono)
            textBox.FontFamily = new Microsoft.UI.Xaml.Media.FontFamily("Consolas");

        return textBox;
    }

    private void Row_FieldChanged(object sender, object e)
    {
        if (!_suppressChanged)
            ItemsChanged?.Invoke(this, EventArgs.Empty);
    }

    private void RowValueKindBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (sender is ComboBox comboBox && comboBox.Parent is Grid row)
            UpdateValueKindVisualState(row);

        Row_FieldChanged(sender, e);
    }

    private async void SelectFormFile_Click(object sender, RoutedEventArgs e)
    {
        if (sender is not Button button || button.Parent is not Grid panel || panel.Parent is not Grid row)
            return;

        var picker = new FileOpenPicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, WinRequest.App.Current.MainWindowHandle);
        picker.FileTypeFilter.Add("*");

        var file = await picker.PickSingleFileAsync();
        if (file == null)
            return;

        var valueBox = FindChild<TextBox>(row, "RowValueBox");
        var pathText = FindChild<TextBlock>(row, "RowFilePathText");
        if (valueBox != null)
            valueBox.Text = file.Path;
        if (pathText != null)
            pathText.Text = file.Path;

        Row_FieldChanged(sender, e);
    }

    private void DeleteRow_Click(object sender, RoutedEventArgs e)
    {
        if (sender is not Button btn)
            return;

        if (btn.Parent is Grid row)
            RowsPanel.Children.Remove(row);

        ItemsChanged?.Invoke(this, EventArgs.Empty);
    }

    private void DisposeAutoCompletes()
    {
        foreach (var ac in _autoCompletes)
            ac.Dispose();
        _autoCompletes.Clear();
    }

    private void AddRow_Click(object sender, RoutedEventArgs e)
    {
        AddRow(true, "", "", "", KeyValueValueKind.Text, false, false);
        ItemsChanged?.Invoke(this, EventArgs.Empty);

        if (RowsPanel.Children.LastOrDefault() is Grid lastRow)
        {
            var keyBox = FindChild<TextBox>(lastRow, "RowKeyBox");
            keyBox?.Focus(FocusState.Programmatic);
        }
    }

    private void UpdateSupportsValueKind()
    {
        if (ValueKindHeaderColumn == null || ValueKindHeaderText == null)
            return;

        ValueKindHeaderColumn.Width = SupportsValueKind ? new GridLength(92) : new GridLength(0);
        ValueKindHeaderText.Visibility = SupportsValueKind ? Visibility.Visible : Visibility.Collapsed;
    }

    private void UpdateValueKindVisualState(Grid row)
    {
        bool isFile = SupportsValueKind && GetSelectedValueKind(FindChild<ComboBox>(row, "RowValueKindBox")) == KeyValueValueKind.File;
        var valueBox = FindChild<TextBox>(row, "RowValueBox");
        var filePanel = FindChild<Grid>(row, "RowFilePickerPanel");
        var pathText = FindChild<TextBlock>(row, "RowFilePathText");

        if (valueBox != null)
            valueBox.Visibility = isFile ? Visibility.Collapsed : Visibility.Visible;
        if (filePanel != null)
            filePanel.Visibility = isFile ? Visibility.Visible : Visibility.Collapsed;
        if (pathText != null && valueBox != null)
            pathText.Text = valueBox.Text;
    }

    private static KeyValueValueKind GetSelectedValueKind(ComboBox? comboBox)
    {
        if (comboBox?.SelectedItem is ComboBoxItem item && item.Tag is KeyValueValueKind kind)
            return kind;

        return KeyValueValueKind.Text;
    }

    private static void OnSupportsValueKindChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is KeyValueTable table)
            table.UpdateSupportsValueKind();
    }

    private static void OnSupportsAutoGeneratedHeadersChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is KeyValueTable table)
            table.UpdateAutoGeneratedHeadersVisibility();
    }

    private void AutoGeneratedHeadersButton_Click(object sender, RoutedEventArgs e)
    {
        _showAutoGeneratedHeaders = !_showAutoGeneratedHeaders;
        UpdateAutoGeneratedHeadersVisibility();
    }

    private void UpdateAutoGeneratedHeadersVisibility()
    {
        if (AutoGeneratedHeadersButton == null)
            return;

        AutoGeneratedHeadersButton.Visibility = SupportsAutoGeneratedHeaders ? Visibility.Visible : Visibility.Collapsed;
        AutoGeneratedHeadersIcon.Glyph = _showAutoGeneratedHeaders ? "\uE8F5" : "\uE890";
        AutoGeneratedHeadersButtonText.Text = _showAutoGeneratedHeaders
            ? "Hide auto-generated headers"
            : "Show auto-generated headers";

        foreach (UIElement child in RowsPanel.Children)
        {
            if (child is Grid row)
                UpdateAutoGeneratedHeadersVisibility(row);
        }
    }

    private void UpdateAutoGeneratedHeadersVisibility(Grid row)
    {
        if (row.Tag is KeyValuePairItem { IsAutoGenerated: true })
            row.Visibility = SupportsAutoGeneratedHeaders && !_showAutoGeneratedHeaders ? Visibility.Collapsed : Visibility.Visible;
    }

    private static List<KeyValuePairItem> MergeAutoGeneratedHeaders(IEnumerable<KeyValuePairItem> items)
    {
        var source = items.Select(CloneItem).ToList();
        var result = new List<KeyValuePairItem>();

        foreach (var defaultHeader in DefaultAutoGeneratedHeaders)
        {
            var existing = source.FirstOrDefault(x =>
                HeaderKeyMatches(x.Key, defaultHeader.Key) ||
                (defaultHeader.Key == "WinRequest-Token" && HeaderKeyMatches(x.Key, "Postman-Token")));

            if (existing != null)
            {
                source.Remove(existing);
                existing.Key = defaultHeader.Key;
                existing.Value = defaultHeader.Value;
                existing.IsAutoGenerated = true;
                existing.IsLocked = defaultHeader.IsLocked;
                if (existing.IsLocked)
                    existing.Enabled = true;
                result.Add(existing);
            }
            else
            {
                result.Add(CloneItem(defaultHeader));
            }
        }

        result.AddRange(source);
        return result;
    }

    private static bool HeaderKeyMatches(string left, string right)
        => string.Equals(left?.Trim(), right, StringComparison.OrdinalIgnoreCase);

    private static KeyValuePairItem CloneItem(KeyValuePairItem source)
    {
        return new KeyValuePairItem
        {
            Key = source.Key,
            Value = source.Value,
            ValueKind = source.ValueKind,
            Description = source.Description,
            Enabled = source.Enabled,
            IsAutoGenerated = source.IsAutoGenerated,
            IsLocked = source.IsLocked
        };
    }

    private static T? FindChild<T>(DependencyObject parent, string name) where T : FrameworkElement
    {
        if (parent is T element && element.Name == name)
            return element;

        int count = VisualTreeHelperGetChildrenCount(parent);
        for (int i = 0; i < count; i++)
        {
            var child = Microsoft.UI.Xaml.Media.VisualTreeHelper.GetChild(parent, i);
            var result = FindChild<T>(child, name);
            if (result != null)
                return result;
        }
        return null;
    }

    private static int VisualTreeHelperGetChildrenCount(DependencyObject parent)
    {
        try { return Microsoft.UI.Xaml.Media.VisualTreeHelper.GetChildrenCount(parent); }
        catch { return 0; }
    }
}
